---
fixtures:
  repositories:
    https://github.com/puppetlabs/puppetlabs-vcsrepo.git
    https://github.com/danielparks/puppet-rustup.git
    https://github.com/puppetlabs/puppetlabs-postgresql.git
